# Example configuration file for program

skins:
  - url: https://steamcommunity.com/market/listings/730/P250%20%7C%20Metallic%20DDPAT%20(Factory%20New)
    float: 0.006126126126126126
    price: 0.25
    number_of_stickers:
    pages:
    pattern:
